# Generated by Django 3.2.12 on 2022-03-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campusrecruiter', '0002_remove_company_companyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=250, null=True)),
                ('MonthlySalary', models.CharField(max_length=250, null=True)),
                ('JobDescriptions', models.CharField(max_length=250, null=True)),
                ('NoofOpenings', models.CharField(max_length=150, null=True)),
                ('JobLocation', models.CharField(max_length=250, null=True)),
                ('ApplyDate', models.DateField(null=True)),
                ('LastDate', models.DateField(null=True)),
                ('JobpostingDate', models.DateTimeField(auto_now_add=True)),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusrecruiter.company')),
            ],
        ),
    ]
