# Generated by Django 3.2.12 on 2022-03-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusrecruiter', '0003_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='user',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='companies',
        ),
        migrations.DeleteModel(
            name='Applyjob',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
