# Generated by Django 3.2.12 on 2022-03-03 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campusrecruiter', '0004_auto_20220303_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactPerson', models.CharField(max_length=255, null=True)),
                ('CompanyUrl', models.CharField(max_length=255, null=True)),
                ('CompanyAddress', models.CharField(max_length=255, null=True)),
                ('MobileNumber', models.CharField(max_length=15, null=True)),
                ('CompanyLogo', models.FileField(max_length=200, null=True, upload_to='')),
                ('CompanyRegdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppID', models.CharField(max_length=255, null=True)),
                ('Messages', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(max_length=255, null=True)),
                ('ResponseDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=250, null=True)),
                ('MonthlySalary', models.CharField(max_length=250, null=True)),
                ('JobDescriptions', models.CharField(max_length=250, null=True)),
                ('NoofOpenings', models.CharField(max_length=150, null=True)),
                ('JobLocation', models.CharField(max_length=250, null=True)),
                ('ApplyDate', models.DateField(null=True)),
                ('LastDate', models.DateField(null=True)),
                ('JobpostingDate', models.DateTimeField(auto_now_add=True)),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusrecruiter.company')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SecondaryBoard', models.CharField(max_length=255, null=True)),
                ('SecondaryBoardyop', models.CharField(max_length=100, null=True)),
                ('SecondaryBoardper', models.CharField(max_length=255, null=True)),
                ('SecondaryBoardcgpa', models.CharField(max_length=255, null=True)),
                ('SSecondaryBoard', models.CharField(max_length=255, null=True)),
                ('SSecondaryBoardyop', models.CharField(max_length=255, null=True)),
                ('SSecondaryBoardper', models.CharField(max_length=255, null=True)),
                ('SSecondaryBoardcgpa', models.CharField(max_length=255, null=True)),
                ('GraUni', models.CharField(max_length=255, null=True)),
                ('GraUniyop', models.CharField(max_length=255, null=True)),
                ('GraUnidper', models.CharField(max_length=255, null=True)),
                ('GraUnicgpa', models.CharField(max_length=255, null=True)),
                ('PGUni', models.CharField(max_length=255, null=True)),
                ('PGUniyop', models.CharField(max_length=255, null=True)),
                ('PGUniper', models.CharField(max_length=255, null=True)),
                ('PGUnicgpa', models.CharField(max_length=255, null=True)),
                ('ExtraCurriculars', models.CharField(max_length=255, null=True)),
                ('OtherAchivement', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileNumber', models.CharField(max_length=15, null=True)),
                ('StudentID', models.CharField(max_length=100, null=True)),
                ('Gender', models.CharField(max_length=15, null=True)),
                ('Address', models.CharField(max_length=300, null=True)),
                ('Age', models.CharField(max_length=15, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Image', models.FileField(max_length=200, null=True, upload_to='')),
                ('ResponseDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applyjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume', models.FileField(max_length=200, null=True, upload_to='')),
                ('ApplyDate', models.DateField(null=True)),
                ('Message', models.CharField(max_length=255, null=True)),
                ('Remark', models.CharField(max_length=255, null=True)),
                ('Status', models.CharField(max_length=255, null=True)),
                ('ResponseDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusrecruiter.vacancy')),
            ],
        ),
    ]
