# Generated by Django 3.2.12 on 2022-03-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusrecruiter', '0005_applyjob_candidate_company_education_message_vacancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applyjob',
        ),
    ]
