# Generated by Django 3.2.12 on 2022-03-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusrecruiter', '0007_applyjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
