# Generated by Django 3.2.12 on 2022-03-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campusrecruiter', '0008_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Messages', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(max_length=255, null=True)),
                ('ResponseDate', models.DateTimeField(auto_now_add=True)),
                ('appjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusrecruiter.applyjob')),
            ],
        ),
    ]
