# Generated by Django 4.2.1 on 2023-05-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusrecruiter', '0012_alter_applyjob_id_alter_candidate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
