# Generated by Django 4.2.1 on 2023-05-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusrecruiter', '0013_workexperience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='Category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
