# Generated by Django 4.2.1 on 2023-06-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusrecruiter', '0017_verifier_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verifier',
        ),
    ]
