# Generated by Django 4.2.1 on 2023-06-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusrecruiter', '0019_company_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ComapnyCard',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
