# Generated by Django 4.2.1 on 2023-06-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusrecruiter', '0020_company_comapnycard'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='Recommanded',
            field=models.BooleanField(null=True),
        ),
    ]
